services:
  smart_home_shop_oltp:
    image: postgres:15
    container_name: smart_home_shop_oltp
    environment:
      POSTGRES_DB: smart_home_shop_oltp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - oltp_data:/var/lib/postgresql/data
      - ./sql/oltp:/docker-entrypoint-initdb.d
      - ./data:/data
    networks:
      - smart_home_network

  smart_home_shop_olap:
    image: postgres:15
    container_name: smart_home_shop_olap
    environment:
      POSTGRES_DB: smart_home_shop_olap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - olap_data:/var/lib/postgresql/data
      - ./sql/olap:/docker-entrypoint-initdb.d
      - ./data:/csv-data
    networks:
      - smart_home_network
    depends_on:
      - smart_home_shop_oltp

volumes:
  oltp_data:
    driver: local
  olap_data:
    driver: local

networks:
  smart_home_network:
    driver: bridge 